[GitHub Actions] Disable sparse constexpr-not-const as it floods with bogus issues
All EXPORT_SYMBOL* results with:
error: non-constant initializer for static object
and sparse failure.

It is not only happening with sound/soc/sof/ but the whole kernel, disable
this warning so we can have usable sparse again.

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
Reviewed-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Reviewed-by: Daniel Baluta <daniel.baluta@nxp.com>
Reviewed-by: Bard Liao <yung-chuan.liao@linux.intel.com>